name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  http: ^1.2.0
  mobile_scanner: ^3.5.7
  flutter_svg: ^2.1.3
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1

  # Firebase Packages
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.0.3
  firebase_storage: ^12.4.10

  # Notifications & Utilities
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.1
  image_picker: ^1.2.1
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.4  # updated

  # File Exporting
  share_plus: ^7.2.0
  pdf: ^3.10.4
  printing: ^5.11.0
  excel: ^2.0.4
  open_filex: ^4.0.4  # updated

  permission_handler: ^11.4.0

  intl: ^0.18.1

  flutter_ringtone_player: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - lib/src/assets/odlfs.jpg
    - lib/src/assets/guardlogo.jpg

flutter_icons:
  android: true
  ios: true
  image_path: "lib/src/assets/app_icon.jpg"