name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^1.2.0
  mobile_scanner: ^3.5.7
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.5.0
  firebase_messaging: ^15.0.3
  awesome_notifications: ^0.9.2
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
